### PR TITLE
Update to allow lib to build using mos 2.12.1

### PR DESCRIPTION
**Pull request by pjaos**
Updated mos to 2.12.1 and this lib failed to build. 

Updated to fix the following error

In file included from /scratch/git_repos/ythermcam/software/huzzah-featherwing/deps/prometheus-metrics/src/esp32/mgos_prometheus_metrics_esp32.c:17:0:
/opt/Espressif/esp-idf/components/freertos/include/freertos/task.h:75:3: error: #error "include FreeRTOS.h must appear in source files before include task.h"
  #error "include FreeRTOS.h must appear in source files before include task.h"
   ^

### CODE REVIEW

**Comment by pimvanpelt** [comment]
Thanks for the PR -- looks good to me, integrating.
